### ISSUE TITLE
[Todo] Make website less busy

### ISSUE THREAD

**Issue by zaydek** [zaydek/heroicons.dev#55]
- [x] Change `py-32` to `py-24` or similar
- [ ] Align icon inside of header
- [ ] Make logos monochrome, show color on hover
- [x] Change top-left links to a more prominent `Fork Me on GitHub`
- [x] Put ‘Thank the designer Tweet’ above or below the CTA? #52
- [ ] Add ‘Become a Sponsor’ link or modal?

Quick mock up (not representational):

<img width="1440" alt="Screen Shot 2020-08-20 at 2 04 05 PM" src="https://user-images.githubusercontent.com/58870766/90718914-0f98fe00-e2ee-11ea-88f6-e79c33cc0198.png">
